import { Pokemon } from "../models/pokemon.model";

export const POKEMON_DATA_V3: Pokemon[] = [
    {
        id: 1,
        name: "bulbasaur",
        koreanName: "이상해씨",
        imageUrl: "1.png",
        types: ["grass", "poison"],
    },
    {
        id: 2,
        name: "ivysaur",
        koreanName: "이상해풀",
        imageUrl: "2.png",
        types: ["grass", "poison"],
    },
    {
        id: 3,
        name: "venusaur",
        koreanName: "이상해꽃",
        imageUrl: "3.png",
        types: ["grass", "poison"],
    },
    {
        id: 4,
        name: "charmander",
        koreanName: "파이리",
        imageUrl: "4.png",
        types: ["fire"],
    },
    {
        id: 5,
        name: "charmeleon",
        koreanName: "리자드",
        imageUrl: "5.png",
        types: ["fire", "dragon"],
    },
    {
        id: 6,
        name: "charizard",
        koreanName: "리자몽",
        imageUrl: "6.png",
        types: ["fire", "dragon"],
    },
    {
        id: 7,
        name: "squirtle",
        koreanName: "꼬부기",
        imageUrl: "7.png",
        types: ["water"],
    },
    {
        id: 8,
        name: "wartortle",
        koreanName: "어니부기",
        imageUrl: "8.png",
        types: ["water"],
    },
    {
        id: 9,
        name: "blastoise",
        koreanName: "거북왕",
        imageUrl: "9.png",
        types: ["water"],
    },
    {
        id: 10,
        name: "caterpie",
        koreanName: "캐터피",
        imageUrl: "10.png",
        types: ["bug"],
    },
    {
        id: 11,
        name: "metapod",
        koreanName: "단데기",
        imageUrl: "11.png",
        types: ["bug"],
    },
    {
        id: 12,
        name: "butterfree",
        koreanName: "버터플",
        imageUrl: "12.png",
        types: ["bug", "flying"],
    },
    {
        id: 13,
        name: "weedle",
        koreanName: "뿔충이",
        imageUrl: "13.png",
        types: ["bug", "poison"],
    },
    {
        id: 14,
        name: "kakuna",
        koreanName: "딱충이",
        imageUrl: "14.png",
        types: ["bug", "poison"],
    },
    {
        id: 15,
        name: "beedrill",
        koreanName: "독침붕",
        imageUrl: "15.png",
        types: ["bug", "poison"],
    },
    {
        id: 16,
        name: "pidgey",
        koreanName: "구구",
        imageUrl: "16.png",
        types: ["normal", "flying"],
    },
    {
        id: 17,
        name: "pidgeotto",
        koreanName: "피죤",
        imageUrl: "17.png",
        types: ["normal", "flying"],
    },
    {
        id: 18,
        name: "pidgeot",
        koreanName: "피죤투",
        imageUrl: "18.png",
        types: ["normal", "flying"],
    },
    {
        id: 19,
        name: "rattata",
        koreanName: "음뱃",
        imageUrl: "714.png",
        types: ["flying", "dragon"],
    },
    {
        id: 20,
        name: "raticate",
        koreanName: "음번",
        imageUrl: "715.png",
        types: ["flying", "dragon"],
    },
    {
        id: 21,
        name: "spearow",
        koreanName: "깨비참",
        imageUrl: "21.png",
        types: ["flying"],
    },
    {
        id: 22,
        name: "fearow",
        koreanName: "깨비드릴조",
        imageUrl: "22.png",
        types: ["flying"],
    },
    {
        id: 23,
        name: "ekans",
        koreanName: "아보",
        imageUrl: "23.png",
        types: ["poison"],
    },
    {
        id: 24,
        name: "arbok",
        koreanName: "아보크",
        imageUrl: "24.png",
        types: ["poison", "dark"],
    },
    {
        id: 25,
        name: "pikachu",
        koreanName: "피카츄",
        imageUrl: "25.png",
        types: ["electric"],
    },
    {
        id: 26,
        name: "raichu",
        koreanName: "라이츄(알로라)",
        imageUrl: "10100.png",
        types: ["electric", "psychic"],
    },
    {
        id: 27,
        name: "sandshrew",
        koreanName: "모래두지(알로라)",
        imageUrl: "10101.png",
        types: ["ice", "steel"],
    },
    {
        id: 28,
        name: "sandslash",
        koreanName: "고지(알로라)",
        imageUrl: "10102.png",
        types: ["ice", "steel"],
    },
    {
        id: 29,
        name: "nidoran-f",
        koreanName: "니드런",
        imageUrl: "29.png",
        types: ["poison"],
    },
    {
        id: 30,
        name: "nidorina",
        koreanName: "니드리나",
        imageUrl: "30.png",
        types: ["poison"],
    },
    {
        id: 31,
        name: "nidoqueen",
        koreanName: "니드퀸",
        imageUrl: "31.png",
        types: ["poison", "ground"],
    },
    {
        id: 32,
        name: "nidoran-m",
        koreanName: "드라꼰",
        imageUrl: "885.png",
        types: ["dragon", "ghost"],
    },
    {
        id: 33,
        name: "nidorino",
        koreanName: "드래런치",
        imageUrl: "886.png",
        types: ["dragon", "ghost"],
    },
    {
        id: 34,
        name: "nidoking",
        koreanName: "드래펄트",
        imageUrl: "887.png",
        types: ["dragon", "ghost"],
    },
    {
        id: 35,
        name: "clefairy",
        koreanName: "삐삐",
        imageUrl: "35.png",
        types: ["normal", "fairy"],
    },
    {
        id: 36,
        name: "clefable",
        koreanName: "픽시",
        imageUrl: "36.png",
        types: ["normal", "fairy"],
    },
    {
        id: 37,
        name: "vulpix",
        koreanName: "식스테일",
        imageUrl: "37.png",
        types: ["fire"],
    },
    {
        id: 38,
        name: "ninetales",
        koreanName: "나인테일",
        imageUrl: "38.png",
        types: ["fire", "fairy"],
    },
    {
        id: 39,
        name: "jigglypuff",
        koreanName: "푸린",
        imageUrl: "39.png",
        types: ["normal", "fairy"],
    },
    {
        id: 40,
        name: "wigglytuff",
        koreanName: "푸크린",
        imageUrl: "40.png",
        types: ["normal", "fairy"],
    },
    {
        id: 41,
        name: "zubat",
        koreanName: "주뱃",
        imageUrl: "41.png",
        types: ["poison", "flying"],
    },
    {
        id: 42,
        name: "golbat",
        koreanName: "골뱃",
        imageUrl: "42.png",
        types: ["poison", "flying"],
    },
    {
        id: 43,
        name: "oddish",
        koreanName: "뚜벅쵸",
        imageUrl: "43.png",
        types: ["grass", "poison"],
    },
    {
        id: 44,
        name: "gloom",
        koreanName: "냄새꼬",
        imageUrl: "44.png",
        types: ["grass", "poison"],
    },
    {
        id: 45,
        name: "vileplume",
        koreanName: "라플레시아",
        imageUrl: "45.png",
        types: ["grass", "poison"],
    },
    {
        id: 46,
        name: "paras",
        koreanName: "파라스",
        imageUrl: "46.png",
        types: ["bug", "grass"],
    },
    {
        id: 47,
        name: "parasect",
        koreanName: "파라섹트",
        imageUrl: "47.png",
        types: ["bug", "grass"],
    },
    {
        id: 48,
        name: "venonat",
        koreanName: "콘팡",
        imageUrl: "48.png",
        types: ["bug", "poison"],
    },
    {
        id: 49,
        name: "venomoth",
        koreanName: "도나리",
        imageUrl: "49.png",
        types: ["bug", "psychic"],
    },
    {
        id: 50,
        name: "diglett",
        koreanName: "파르빗",
        imageUrl: "659.png",
        types: ["normal"],
    },
    {
        id: 51,
        name: "dugtrio",
        koreanName: "파르토",
        imageUrl: "660.png",
        types: ["normal", "ground"],
    },
    {
        id: 52,
        name: "meowth",
        koreanName: "들눈해",
        imageUrl: "948.png",
        types: ["ground", "grass"],
    },
    {
        id: 53,
        name: "persian",
        koreanName: "육파리",
        imageUrl: "53.png",
        types: ["ground", "grass"],
    },
    {
        id: 54,
        name: "psyduck",
        koreanName: "오케이징",
        imageUrl: "686.png",
        types: ["dark", "psychic"],
    },
    {
        id: 55,
        name: "golduck",
        koreanName: "칼라마네로",
        imageUrl: "687.png",
        types: ["dark", "psychic"],
    },
    {
        id: 56,
        name: "mankey",
        koreanName: "망키",
        imageUrl: "56.png",
        types: ["fighting"],
    },
    {
        id: 57,
        name: "primeape",
        koreanName: "성원숭",
        imageUrl: "57.png",
        types: ["fighting"],
    },
    {
        id: 58,
        name: "growlithe",
        koreanName: "가디",
        imageUrl: "58.png",
        types: ["fire"],
    },
    {
        id: 59,
        name: "arcanine",
        koreanName: "윈디",
        imageUrl: "59.png",
        types: ["fire"],
    },
    {
        id: 60,
        name: "poliwag",
        koreanName: "발챙이",
        imageUrl: "60.png",
        types: ["water"],
    },
    {
        id: 61,
        name: "poliwhirl",
        koreanName: "슈륙챙이",
        imageUrl: "61.png",
        types: ["water"],
    },
    {
        id: 62,
        name: "poliwrath",
        koreanName: "강챙이",
        imageUrl: "62.png",
        types: ["water", "fighting"],
    },
    {
        id: 63,
        name: "abra",
        koreanName: "캐이시",
        imageUrl: "63.png",
        types: ["psychic"],
    },
    {
        id: 64,
        name: "kadabra",
        koreanName: "윤겔라",
        imageUrl: "64.png",
        types: ["psychic"],
    },
    {
        id: 65,
        name: "alakazam",
        koreanName: "후딘",
        imageUrl: "65.png",
        types: ["psychic"],
    },
    {
        id: 66,
        name: "machop",
        koreanName: "치고마",
        imageUrl: "66.png",
        types: ["fighting"],
    },
    {
        id: 67,
        name: "machoke",
        koreanName: "우라오스(일격)",
        imageUrl: "891.png",
        types: ["fighting", "dark"],
    },
    {
        id: 68,
        name: "machamp",
        koreanName: "우라오스(연격)",
        imageUrl: "10191.png",
        types: ["fighting", "water"],
    },
    {
        id: 69,
        name: "bellsprout",
        koreanName: "모다피",
        imageUrl: "893.png",
        types: ["grass", "poison"],
    },
    {
        id: 70,
        name: "weepinbell",
        koreanName: "우츠동",
        imageUrl: "70.png",
        types: ["grass", "poison"],
    },
    {
        id: 71,
        name: "victreebel",
        koreanName: "우츠보트",
        imageUrl: "71.png",
        types: ["grass", "poison"],
    },
    {
        id: 72,
        name: "tentacool",
        koreanName: "왕눈해",
        imageUrl: "72.png",
        types: ["water", "poison"],
    },
    {
        id: 73,
        name: "tentacruel",
        koreanName: "독파리",
        imageUrl: "73.png",
        types: ["water", "poison"],
    },
    {
        id: 74,
        name: "geodude",
        koreanName: "베베솔트",
        imageUrl: "932.png",
        types: ["rock"],
    },
    {
        id: 75,
        name: "graveler",
        koreanName: "스태솔트",
        imageUrl: "933.png",
        types: ["rock"],
    },
    {
        id: 76,
        name: "golem",
        koreanName: "콜로솔트",
        imageUrl: "934.png",
        types: ["rock"],
    },
    {
        id: 77,
        name: "ponyta",
        koreanName: "포니타",
        imageUrl: "77.png",
        types: ["fire"],
    },
    {
        id: 78,
        name: "rapidash",
        koreanName: "날쌩마",
        imageUrl: "78.png",
        types: ["fire", "fairy"],
    },
    {
        id: 79,
        name: "slowpoke",
        koreanName: "야돈",
        imageUrl: "79.png",
        types: ["water", "psychic"],
    },
    {
        id: 80,
        name: "slowbro",
        koreanName: "야도란",
        imageUrl: "80.png",
        types: ["water", "psychic"],
    },
    {
        id: 81,
        name: "magnemite",
        koreanName: "코일",
        imageUrl: "81.png",
        types: ["electric", "steel"],
    },
    {
        id: 82,
        name: "magneton",
        koreanName: "레어코일",
        imageUrl: "82.png",
        types: ["electric", "steel"],
    },
    {
        id: 83,
        name: "farfetchd",
        koreanName: "창파나이트",
        imageUrl: "865.png",
        types: ["fighting"],
    },
    {
        id: 84,
        name: "doduo",
        koreanName: "두두",
        imageUrl: "84.png",
        types: ["normal", "flying"],
    },
    {
        id: 85,
        name: "dodrio",
        koreanName: "두트리오",
        imageUrl: "85.png",
        types: ["fighting", "flying"],
    },
    {
        id: 86,
        name: "seel",
        koreanName: "짜랑랑",
        imageUrl: "753.png",
        types: ["grass", "fairy"],
    },
    {
        id: 87,
        name: "dewgong",
        koreanName: "라란티스",
        imageUrl: "754.png",
        types: ["grass", "fairy"],
    },
    {
        id: 88,
        name: "grimer",
        koreanName: "질퍽이",
        imageUrl: "88.png",
        types: ["poison"],
    },
    {
        id: 89,
        name: "muk",
        koreanName: "질뻐기",
        imageUrl: "89.png",
        types: ["poison"],
    },
    {
        id: 90,
        name: "shellder",
        koreanName: "셀러",
        imageUrl: "90.png",
        types: ["water", "ice"],
    },
    {
        id: 91,
        name: "cloyster",
        koreanName: "파르셀",
        imageUrl: "91.png",
        types: ["water", "ice"],
    },
    {
        id: 92,
        name: "gastly",
        koreanName: "고오스",
        imageUrl: "92.png",
        types: ["ghost", "poison"],
    },
    {
        id: 93,
        name: "haunter",
        koreanName: "고우스트",
        imageUrl: "93.png",
        types: ["ghost", "poison"],
    },
    {
        id: 94,
        name: "gengar",
        koreanName: "팬텀",
        imageUrl: "94.png",
        types: ["ghost", "poison"],
    },
    {
        id: 95,
        name: "onix",
        koreanName: "나몰빼미",
        imageUrl: "722.png",
        types: ["grass", "flying"],
    },
    {
        id: 96,
        name: "drowzee",
        koreanName: "빼미스로우",
        imageUrl: "723.png",
        types: ["grass", "flying"],
    },
    {
        id: 97,
        name: "hypno",
        koreanName: "모크나이퍼",
        imageUrl: "724.png",
        types: ["grass", "ghost"],
    },
    {
        id: 98,
        name: "krabby",
        koreanName: "냐오불",
        imageUrl: "725.png",
        types: ["fire"],
    },
    {
        id: 99,
        name: "kingler",
        koreanName: "냐오히트",
        imageUrl: "726.png",
        types: ["fire"],
    },
    {
        id: 100,
        name: "voltorb",
        koreanName: "어흥염",
        imageUrl: "727.png",
        types: ["fire", "dark"],
    },
    {
        id: 101,
        name: "electrode",
        koreanName: "누리공",
        imageUrl: "728.png",
        types: ["water"],
    },
    {
        id: 102,
        name: "exeggcute",
        koreanName: "키요공",
        imageUrl: "728.png",
        types: ["water"],
    },
    {
        id: 103,
        name: "exeggutor",
        koreanName: "누리레느",
        imageUrl: "730.png",
        types: ["water", "fairy"],
    },
    {
        id: 104,
        name: "cubone",
        koreanName: "탕구리",
        imageUrl: "104.png",
        types: ["ground"],
    },
    {
        id: 105,
        name: "marowak",
        koreanName: "텅구리",
        imageUrl: "105.png",
        types: ["ground"],
    },
    {
        id: 106,
        name: "hitmonlee",
        koreanName: "완철포",
        imageUrl: "692.png",
        types: ["water"],
    },
    {
        id: 107,
        name: "hitmonchan",
        koreanName: "블로스터",
        imageUrl: "693.png",
        types: ["water"],
    },
    {
        id: 108,
        name: "lickitung",
        koreanName: "내루미",
        imageUrl: "108.png",
        types: ["normal"],
    },
    {
        id: 109,
        name: "koffing",
        koreanName: "또가스",
        imageUrl: "109.png",
        types: ["poison"],
    },
    {
        id: 110,
        name: "weezing",
        koreanName: "또도가스",
        imageUrl: "110.png",
        types: ["poison"],
    },
    {
        id: 111,
        name: "rhyhorn",
        koreanName: "뿔카노",
        imageUrl: "111.png",
        types: ["ground", "rock"],
    },
    {
        id: 112,
        name: "rhydon",
        koreanName: "코뿌리",
        imageUrl: "112.png",
        types: ["ground", "rock"],
    },
    {
        id: 113,
        name: "chansey",
        koreanName: "럭키",
        imageUrl: "113.png",
        types: ["normal"],
    },
    {
        id: 114,
        name: "tangela",
        koreanName: "덩쿠리",
        imageUrl: "114.png",
        types: ["grass", "ghost"],
    },
    {
        id: 115,
        name: "kangaskhan",
        koreanName: "캥카",
        imageUrl: "115.png",
        types: ["normal"],
    },
    {
        id: 116,
        name: "horsea",
        koreanName: "쏘드라",
        imageUrl: "116.png",
        types: ["water"],
    },
    {
        id: 117,
        name: "seadra",
        koreanName: "시드라",
        imageUrl: "117.png",
        types: ["water"],
    },
    {
        id: 118,
        name: "goldeen",
        koreanName: "터벅고래",
        imageUrl: "974.png",
        types: ["ice"],
    },
    {
        id: 119,
        name: "seaking",
        koreanName: "우락고래",
        imageUrl: "975.png",
        types: ["ice"],
    },
    {
        id: 120,
        name: "staryu",
        koreanName: "별가사리",
        imageUrl: "120.png",
        types: ["water"],
    },
    {
        id: 121,
        name: "starmie",
        koreanName: "아쿠스타",
        imageUrl: "121.png",
        types: ["water", "psychic"],
    },
    {
        id: 122,
        name: "mr-mime",
        koreanName: "우렁찬꼬리",
        imageUrl: "985.png",
        types: ["fairy", "psychic"],
    },
    {
        id: 123,
        name: "scyther",
        koreanName: "스라크",
        imageUrl: "123.png",
        types: ["bug", "flying"],
    },
    {
        id: 124,
        name: "jynx",
        koreanName: "루주라",
        imageUrl: "124.png",
        types: ["ice", "psychic"],
    },
    {
        id: 125,
        name: "electabuzz",
        koreanName: "에레브",
        imageUrl: "125.png",
        types: ["electric"],
    },
    {
        id: 126,
        name: "magmar",
        koreanName: "마그마",
        imageUrl: "126.png",
        types: ["fire"],
    },
    {
        id: 127,
        name: "pinsir",
        koreanName: "쁘사이저",
        imageUrl: "127.png",
        types: ["bug", "ground"],
    },
    {
        id: 128,
        name: "tauros",
        koreanName: "할비롱",
        imageUrl: "780.png",
        types: ["normal", "dragon"],
    },
    {
        id: 129,
        name: "magikarp",
        koreanName: "잉어킹",
        imageUrl: "129.png",
        types: ["water"],
    },
    {
        id: 130,
        name: "gyarados",
        koreanName: "갸라도스",
        imageUrl: "130.png",
        types: ["water", "dragon"],
    },
    {
        id: 131,
        name: "lapras",
        koreanName: "라프라스",
        imageUrl: "131.png",
        types: ["water", "ice"],
    },
    {
        id: 132,
        name: "ditto",
        koreanName: "메타몽",
        imageUrl: "132.png",
        types: ["normal"],
    },
    {
        id: 133,
        name: "eevee",
        koreanName: "이브이",
        imageUrl: "133.png",
        types: ["normal"],
    },
    {
        id: 134,
        name: "vaporeon",
        koreanName: "샤미드",
        imageUrl: "134.png",
        types: ["water"],
    },
    {
        id: 135,
        name: "jolteon",
        koreanName: "쥬피썬더",
        imageUrl: "135.png",
        types: ["electric"],
    },
    {
        id: 136,
        name: "flareon",
        koreanName: "부스터",
        imageUrl: "136.png",
        types: ["fire"],
    },
    {
        id: 137,
        name: "porygon",
        koreanName: "폴리곤",
        imageUrl: "137.png",
        types: ["normal"],
    },
    {
        id: 138,
        name: "omanyte",
        koreanName: "암나이트",
        imageUrl: "138.png",
        types: ["rock", "water"],
    },
    {
        id: 139,
        name: "omastar",
        koreanName: "암스타",
        imageUrl: "139.png",
        types: ["rock", "water"],
    },
    {
        id: 140,
        name: "kabuto",
        koreanName: "투구",
        imageUrl: "140.png",
        types: ["rock", "water"],
    },
    {
        id: 141,
        name: "kabutops",
        koreanName: "투구푸스",
        imageUrl: "141.png",
        types: ["rock", "water"],
    },
    {
        id: 142,
        name: "aerodactyl",
        koreanName: "프테라",
        imageUrl: "142.png",
        types: ["rock", "flying"],
    },
    {
        id: 143,
        name: "snorlax",
        koreanName: "잠만보",
        imageUrl: "143.png",
        types: ["normal"],
    },
    {
        id: 144,
        name: "articuno",
        koreanName: "프리져",
        imageUrl: "144.png",
        types: ["ice", "flying"],
    },
    {
        id: 145,
        name: "zapdos",
        koreanName: "썬더",
        imageUrl: "145.png",
        types: ["electric", "flying"],
    },
    {
        id: 146,
        name: "moltres",
        koreanName: "파이어",
        imageUrl: "146.png",
        types: ["fire", "flying"],
    },
    {
        id: 147,
        name: "dratini",
        koreanName: "미뇽",
        imageUrl: "147.png",
        types: ["dragon"],
    },
    {
        id: 148,
        name: "dragonair",
        koreanName: "신뇽",
        imageUrl: "148.png",
        types: ["dragon"],
    },
    {
        id: 149,
        name: "dragonite",
        koreanName: "망나뇽",
        imageUrl: "149.png",
        types: ["dragon", "flying"],
    },
    {
        id: 150,
        name: "mewtwo",
        koreanName: "뮤츠",
        imageUrl: "150.png",
        types: ["psychic"],
    },
    {
        id: 151,
        name: "mew",
        koreanName: "뮤",
        imageUrl: "151.png",
        types: ["psychic"],
    },
    {
        id: 152,
        name: "chikorita",
        koreanName: "치코리타",
        imageUrl: "152.png",
        types: ["grass"],
    },
    {
        id: 153,
        name: "bayleef",
        koreanName: "베이리프",
        imageUrl: "153.png",
        types: ["grass", "fairy"],
    },
    {
        id: 154,
        name: "meganium",
        koreanName: "메가니움",
        imageUrl: "154.png",
        types: ["grass", "fairy"],
    },
    {
        id: 155,
        name: "cyndaquil",
        koreanName: "브케인",
        imageUrl: "155.png",
        types: ["fire"],
    },
    {
        id: 156,
        name: "quilava",
        koreanName: "마그케인",
        imageUrl: "156.png",
        types: ["fire"],
    },
    {
        id: 157,
        name: "typhlosion",
        koreanName: "블레이범",
        imageUrl: "157.png",
        types: ["fire"],
    },
    {
        id: 158,
        name: "totodile",
        koreanName: "리아코",
        imageUrl: "158.png",
        types: ["water"],
    },
    {
        id: 159,
        name: "croconaw",
        koreanName: "엘리게이",
        imageUrl: "159.png",
        types: ["water"],
    },
    {
        id: 160,
        name: "feraligatr",
        koreanName: "장크로다일",
        imageUrl: "160.png",
        types: ["water"],
    },
    {
        id: 161,
        name: "sentret",
        koreanName: "꼬리선",
        imageUrl: "161.png",
        types: ["normal"],
    },
    {
        id: 162,
        name: "furret",
        koreanName: "다꼬리",
        imageUrl: "162.png",
        types: ["normal"],
    },
    {
        id: 163,
        name: "hoothoot",
        koreanName: "초롱순",
        imageUrl: "969.png",
        types: ["rock", "poison"],
    },
    {
        id: 164,
        name: "noctowl",
        koreanName: "킬라플로르",
        imageUrl: "970.png",
        types: ["rock", "poison"],
    },
    {
        id: 165,
        name: "ledyba",
        koreanName: "나목령",
        imageUrl: "708.png",
        types: ["ghost", "grass"],
    },
    {
        id: 166,
        name: "ledian",
        koreanName: "대로트",
        imageUrl: "709.png",
        types: ["ghost", "grass"],
    },
    {
        id: 167,
        name: "spinarak",
        koreanName: "다투곰",
        imageUrl: "901.png",
        types: ["ground", "normal"],
    },
    {
        id: 168,
        name: "ariados",
        koreanName: "사마자르",
        imageUrl: "900.png",
        types: ["bug", "rock"],
    },
    {
        id: 169,
        name: "crobat",
        koreanName: "크로뱃",
        imageUrl: "169.png",
        types: ["poison", "flying"],
    },
    {
        id: 170,
        name: "chinchou",
        koreanName: "초라기",
        imageUrl: "170.png",
        types: ["water", "electric"],
    },
    {
        id: 171,
        name: "lanturn",
        koreanName: "랜턴",
        imageUrl: "171.png",
        types: ["water", "electric"],
    },
    {
        id: 172,
        name: "pichu",
        koreanName: "피츄",
        imageUrl: "172.png",
        types: ["electric"],
    },
    {
        id: 173,
        name: "cleffa",
        koreanName: "삐",
        imageUrl: "173.png",
        types: ["normal", "fairy"],
    },
    {
        id: 174,
        name: "igglybuff",
        koreanName: "푸푸린",
        imageUrl: "174.png",
        types: ["normal", "fairy"],
    },
    {
        id: 175,
        name: "togepi",
        koreanName: "토게피",
        imageUrl: "175.png",
        types: ["fairy"],
    },
    {
        id: 176,
        name: "togetic",
        koreanName: "토게틱",
        imageUrl: "176.png",
        types: ["fairy", "flying"],
    },
    {
        id: 177,
        name: "natu",
        koreanName: "목도리키텔",
        imageUrl: "694.png",
        types: ["electric", "normal"],
    },
    {
        id: 178,
        name: "xatu",
        koreanName: "일레도리자드",
        imageUrl: "695.png",
        types: ["electric", "normal"],
    },
    {
        id: 179,
        name: "mareep",
        koreanName: "메리프",
        imageUrl: "179.png",
        types: ["electric"],
    },
    {
        id: 180,
        name: "flaaffy",
        koreanName: "보송송",
        imageUrl: "180.png",
        types: ["electric"],
    },
    {
        id: 181,
        name: "ampharos",
        koreanName: "전룡",
        imageUrl: "181.png",
        types: ["electric", "dragon"],
    },
    {
        id: 182,
        name: "bellossom",
        koreanName: "아르코",
        imageUrl: "182.png",
        types: ["grass"],
    },
    {
        id: 183,
        name: "marill",
        koreanName: "마릴",
        imageUrl: "183.png",
        types: ["water", "fairy"],
    },
    {
        id: 184,
        name: "azumarill",
        koreanName: "마릴리",
        imageUrl: "184.png",
        types: ["water", "fairy"],
    },
    {
        id: 185,
        name: "sudowoodo",
        koreanName: "마기아나",
        imageUrl: "801.png",
        types: ["steel", "fairy"],
    },
    {
        id: 186,
        name: "politoed",
        koreanName: "왕구리",
        imageUrl: "186.png",
        types: ["water", "normal"],
    },
    {
        id: 187,
        name: "hoppip",
        koreanName: "통통코",
        imageUrl: "187.png",
        types: ["grass", "flying"],
    },
    {
        id: 188,
        name: "skiploom",
        koreanName: "두코",
        imageUrl: "188.png",
        types: ["grass", "flying"],
    },
    {
        id: 189,
        name: "jumpluff",
        koreanName: "솜솜코",
        imageUrl: "189.png",
        types: ["grass", "flying"],
    },
    {
        id: 190,
        name: "aipom",
        koreanName: "에이팜",
        imageUrl: "190.png",
        types: ["normal"],
    },
    {
        id: 191,
        name: "sunkern",
        koreanName: "캡싸이",
        imageUrl: "951.png",
        types: ["grass"],
    },
    {
        id: 192,
        name: "sunflora",
        koreanName: "스코빌런",
        imageUrl: "952.png",
        types: ["grass", "fire"],
    },
    {
        id: 193,
        name: "yanma",
        koreanName: "왕자리",
        imageUrl: "193.png",
        types: ["bug", "flying"],
    },
    {
        id: 194,
        name: "wooper",
        koreanName: "우파",
        imageUrl: "194.png",
        types: ["water", "ground"],
    },
    {
        id: 195,
        name: "quagsire",
        koreanName: "누오",
        imageUrl: "195.png",
        types: ["water", "ground"],
    },
    {
        id: 196,
        name: "espeon",
        koreanName: "에브이",
        imageUrl: "196.png",
        types: ["psychic"],
    },
    {
        id: 197,
        name: "umbreon",
        koreanName: "블래키",
        imageUrl: "197.png",
        types: ["dark"],
    },
    {
        id: 198,
        name: "murkrow",
        koreanName: "니로우",
        imageUrl: "198.png",
        types: ["dark", "flying"],
    },
    {
        id: 199,
        name: "slowking",
        koreanName: "야도킹 (가라르)",
        imageUrl: "10172.png",
        types: ["poison", "psychic"],
    },
    {
        id: 200,
        name: "misdreavus",
        koreanName: "무우마",
        imageUrl: "200.png",
        types: ["ghost"],
    },
    {
        id: 201,
        name: "unown",
        koreanName: "안농",
        imageUrl: "201.png",
        types: ["psychic"],
    },
    {
        id: 202,
        name: "wobbuffet",
        koreanName: "마자용",
        imageUrl: "202.png",
        types: ["psychic"],
    },
    {
        id: 203,
        name: "girafarig",
        koreanName: "키키링",
        imageUrl: "981.png",
        types: ["normal", "psychic"],
    },
    {
        id: 204,
        name: "pineco",
        koreanName: "꼬시레",
        imageUrl: "767.png",
        types: ["bug", "water"],
    },
    {
        id: 205,
        name: "forretress",
        koreanName: "갑주무사",
        imageUrl: "768.png",
        types: ["bug", "water"],
    },
    {
        id: 206,
        name: "dunsparce",
        koreanName: "노고고치",
        imageUrl: "982.png",
        types: ["normal"],
    },
    {
        id: 207,
        name: "gligar",
        koreanName: "글라이거",
        imageUrl: "207.png",
        types: ["ground", "flying"],
    },
    {
        id: 208,
        name: "steelix",
        koreanName: "님피아",
        imageUrl: "700.png",
        types: ["fairy"],
    },
    {
        id: 209,
        name: "snubbull",
        koreanName: "블루",
        imageUrl: "209.png",
        types: ["dark", "fairy"],
    },
    {
        id: 210,
        name: "granbull",
        koreanName: "그랑블루",
        imageUrl: "210.png",
        types: ["dark", "fairy"],
    },
    {
        id: 211,
        name: "qwilfish",
        koreanName: "침바루(히스이)",
        imageUrl: "10234.png",
        types: ["dark", "poison"],
    },
    {
        id: 212,
        name: "scizor",
        koreanName: "핫삼",
        imageUrl: "212.png",
        types: ["bug", "steel"],
    },
    {
        id: 213,
        name: "shuckle",
        koreanName: "날개치는머리",
        imageUrl: "987.png",
        types: ["ghost", "fairy"],
    },
    {
        id: 214,
        name: "heracross",
        koreanName: "헤라크로스",
        imageUrl: "214.png",
        types: ["bug", "fighting"],
    },
    {
        id: 215,
        name: "sneasel",
        koreanName: "포푸니",
        imageUrl: "215.png",
        types: ["dark", "ice"],
    },
    {
        id: 216,
        name: "teddiursa",
        koreanName: "깜지곰",
        imageUrl: "216.png",
        types: ["normal"],
    },
    {
        id: 217,
        name: "ursaring",
        koreanName: "링곰",
        imageUrl: "217.png",
        types: ["normal"],
    },
    {
        id: 218,
        name: "slugma",
        koreanName: "마그마그",
        imageUrl: "218.png",
        types: ["fire", "rock"],
    },
    {
        id: 219,
        name: "magcargo",
        koreanName: "마그카르고",
        imageUrl: "219.png",
        types: ["fire", "rock"],
    },
    {
        id: 220,
        name: "swinub",
        koreanName: "꾸꾸리",
        imageUrl: "220.png",
        types: ["ice", "ground"],
    },
    {
        id: 221,
        name: "piloswine",
        koreanName: "메꾸리",
        imageUrl: "221.png",
        types: ["ice", "ground"],
    },
    {
        id: 222,
        name: "corsola",
        koreanName: "산호르곤",
        imageUrl: "864.png",
        types: ["ghost"],
    },
    {
        id: 223,
        name: "remoraid",
        koreanName: "총어",
        imageUrl: "223.png",
        types: ["water"],
    },
    {
        id: 224,
        name: "octillery",
        koreanName: "대포무노",
        imageUrl: "224.png",
        types: ["water", "fire"],
    },
    {
        id: 225,
        name: "delibird",
        koreanName: "무쇠보따리",
        imageUrl: "991.png",
        types: ["ice", "water"],
    },
    {
        id: 226,
        name: "mantine",
        koreanName: "데스판",
        imageUrl: "867.png",
        types: ["ground", "ghost"],
    },
    {
        id: 227,
        name: "skarmory",
        koreanName: "무장조",
        imageUrl: "227.png",
        types: ["steel", "flying"],
    },
    {
        id: 228,
        name: "houndour",
        koreanName: "델빌",
        imageUrl: "228.png",
        types: ["dark", "fire"],
    },
    {
        id: 229,
        name: "houndoom",
        koreanName: "헬가",
        imageUrl: "229.png",
        types: ["dark", "fire"],
    },
    {
        id: 230,
        name: "kingdra",
        koreanName: "킹드라",
        imageUrl: "230.png",
        types: ["water", "dragon"],
    },
    {
        id: 231,
        name: "phanpy",
        koreanName: "코코리",
        imageUrl: "231.png",
        types: ["ground"],
    },
    {
        id: 232,
        name: "donphan",
        koreanName: "코리갑",
        imageUrl: "232.png",
        types: ["ground"],
    },
    {
        id: 233,
        name: "porygon2",
        koreanName: "폴리곤2",
        imageUrl: "233.png",
        types: ["normal"],
    },
    {
        id: 234,
        name: "stantler",
        koreanName: "신비록",
        imageUrl: "899.png",
        types: ["normal", "psychic"],
    },
    {
        id: 235,
        name: "smeargle",
        koreanName: "루브도",
        imageUrl: "235.png",
        types: ["normal"],
    },
    {
        id: 236,
        name: "tyrogue",
        koreanName: "수레기",
        imageUrl: "690.png",
        types: ["poison", "water"],
    },
    {
        id: 237,
        name: "hitmontop",
        koreanName: "드래캄",
        imageUrl: "691.png",
        types: ["poison", "dragon"],
    },
    {
        id: 238,
        name: "smoochum",
        koreanName: "뽀뽀라",
        imageUrl: "238.png",
        types: ["ice", "psychic"],
    },
    {
        id: 239,
        name: "elekid",
        koreanName: "에레키드",
        imageUrl: "239.png",
        types: ["electric"],
    },
    {
        id: 240,
        name: "magby",
        koreanName: "마그비",
        imageUrl: "240.png",
        types: ["fire"],
    },
    {
        id: 241,
        name: "miltank",
        koreanName: "밀탱크",
        imageUrl: "241.png",
        types: ["normal"],
    },
    {
        id: 242,
        name: "blissey",
        koreanName: "해피너스",
        imageUrl: "242.png",
        types: ["normal"],
    },
    {
        id: 243,
        name: "raikou",
        koreanName: "라이코",
        imageUrl: "243.png",
        types: ["electric"],
    },
    {
        id: 244,
        name: "entei",
        koreanName: "앤테이",
        imageUrl: "244.png",
        types: ["fire"],
    },
    {
        id: 245,
        name: "suicune",
        koreanName: "스이쿤",
        imageUrl: "245.png",
        types: ["water"],
    },
    {
        id: 246,
        name: "larvitar",
        koreanName: "애버라스",
        imageUrl: "246.png",
        types: ["rock", "ground"],
    },
    {
        id: 247,
        name: "pupitar",
        koreanName: "데기라스",
        imageUrl: "247.png",
        types: ["rock", "ground"],
    },
    {
        id: 248,
        name: "tyranitar",
        koreanName: "마기라스",
        imageUrl: "248.png",
        types: ["rock", "dark"],
    },
    {
        id: 249,
        name: "lugia",
        koreanName: "루기아",
        imageUrl: "249.png",
        types: ["psychic", "flying"],
    },
    {
        id: 250,
        name: "ho-oh",
        koreanName: "칠색조",
        imageUrl: "250.png",
        types: ["fire", "flying"],
    },
    {
        id: 251,
        name: "celebi",
        koreanName: "세레비",
        imageUrl: "251.png",
        types: ["grass", "fairy"],
    },
    {
        id: 252,
        name: "treecko",
        koreanName: "나무지기",
        imageUrl: "252.png",
        types: ["grass"],
    },
    {
        id: 253,
        name: "grovyle",
        koreanName: "나무돌이",
        imageUrl: "253.png",
        types: ["grass"],
    },
    {
        id: 254,
        name: "sceptile",
        koreanName: "나무킹",
        imageUrl: "254.png",
        types: ["grass", "dragon"],
    },
    {
        id: 255,
        name: "torchic",
        koreanName: "아차모",
        imageUrl: "255.png",
        types: ["fire"],
    },
    {
        id: 256,
        name: "combusken",
        koreanName: "영치코",
        imageUrl: "256.png",
        types: ["fire", "fighting"],
    },
    {
        id: 257,
        name: "blaziken",
        koreanName: "번치코",
        imageUrl: "257.png",
        types: ["fire", "fighting"],
    },
    {
        id: 258,
        name: "mudkip",
        koreanName: "물짱이",
        imageUrl: "258.png",
        types: ["water"],
    },
    {
        id: 259,
        name: "marshtomp",
        koreanName: "늪짱이",
        imageUrl: "259.png",
        types: ["water", "ground"],
    },
    {
        id: 260,
        name: "swampert",
        koreanName: "대짱이",
        imageUrl: "260.png",
        types: ["water", "ground"],
    },
    {
        id: 261,
        name: "poochyena",
        koreanName: "나오하",
        imageUrl: "906.png",
        types: ["grass"],
    },
    {
        id: 262,
        name: "mightyena",
        koreanName: "나로테",
        imageUrl: "907.png",
        types: ["grass"],
    },
    {
        id: 263,
        name: "zigzagoon",
        koreanName: "마스카나",
        imageUrl: "908.png",
        types: ["grass", "dark"],
    },
    {
        id: 264,
        name: "linoone",
        koreanName: "푸호꼬",
        imageUrl: "653.png",
        types: ["fire"],
    },
    {
        id: 265,
        name: "wurmple",
        koreanName: "테르나",
        imageUrl: "654.png",
        types: ["fire", "psychic"],
    },
    {
        id: 266,
        name: "silcoon",
        koreanName: "마폭시",
        imageUrl: "655.png",
        types: ["fire", "psychic"],
    },
    {
        id: 267,
        name: "beautifly",
        koreanName: "개구마르",
        imageUrl: "656.png",
        types: ["water"],
    },
    {
        id: 268,
        name: "cascoon",
        koreanName: "개굴반장",
        imageUrl: "657.png",
        types: ["water"],
    },
    {
        id: 269,
        name: "dustox",
        koreanName: "개굴닌자",
        imageUrl: "658.png",
        types: ["water", "dark"],
    },
    {
        id: 270,
        name: "lotad",
        koreanName: "연꽃몬",
        imageUrl: "270.png",
        types: ["water", "grass"],
    },
    {
        id: 271,
        name: "lombre",
        koreanName: "로토스",
        imageUrl: "271.png",
        types: ["water", "grass"],
    },
    {
        id: 272,
        name: "ludicolo",
        koreanName: "로파파",
        imageUrl: "272.png",
        types: ["water", "grass"],
    },
    {
        id: 273,
        name: "seedot",
        koreanName: "몸지브림",
        imageUrl: "856.png",
        types: ["psychic"],
    },
    {
        id: 274,
        name: "nuzleaf",
        koreanName: "손지브림",
        imageUrl: "857.png",
        types: ["psychic"],
    },
    {
        id: 275,
        name: "shiftry",
        koreanName: "브리무음",
        imageUrl: "858.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 276,
        name: "taillow",
        koreanName: "테일로",
        imageUrl: "276.png",
        types: ["normal", "flying"],
    },
    {
        id: 277,
        name: "swellow",
        koreanName: "스왈로",
        imageUrl: "277.png",
        types: ["normal", "flying"],
    },
    {
        id: 278,
        name: "wingull",
        koreanName: "갈모매",
        imageUrl: "278.png",
        types: ["water", "flying"],
    },
    {
        id: 279,
        name: "pelipper",
        koreanName: "패리퍼",
        imageUrl: "279.png",
        types: ["water", "flying"],
    },
    {
        id: 280,
        name: "ralts",
        koreanName: "랄토스",
        imageUrl: "280.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 281,
        name: "kirlia",
        koreanName: "킬리아",
        imageUrl: "281.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 282,
        name: "gardevoir",
        koreanName: "가디안",
        imageUrl: "282.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 283,
        name: "surskit",
        koreanName: "비구술",
        imageUrl: "283.png",
        types: ["bug", "water"],
    },
    {
        id: 284,
        name: "masquerain",
        koreanName: "비나방",
        imageUrl: "284.png",
        types: ["bug", "water"],
    },
    {
        id: 285,
        name: "shroomish",
        koreanName: "버섯꼬",
        imageUrl: "285.png",
        types: ["grass"],
    },
    {
        id: 286,
        name: "breloom",
        koreanName: "버섯모",
        imageUrl: "286.png",
        types: ["grass", "fighting"],
    },
    {
        id: 287,
        name: "slakoth",
        koreanName: "게을로",
        imageUrl: "287.png",
        types: ["normal"],
    },
    {
        id: 288,
        name: "vigoroth",
        koreanName: "발바로",
        imageUrl: "288.png",
        types: ["normal"],
    },
    {
        id: 289,
        name: "slaking",
        koreanName: "게을킹",
        imageUrl: "289.png",
        types: ["normal"],
    },
    {
        id: 290,
        name: "nincada",
        koreanName: "토중몬",
        imageUrl: "290.png",
        types: ["bug", "ground"],
    },
    {
        id: 291,
        name: "ninjask",
        koreanName: "아이스크",
        imageUrl: "291.png",
        types: ["bug", "flying"],
    },
    {
        id: 292,
        name: "shedinja",
        koreanName: "껍질몬",
        imageUrl: "292.png",
        types: ["bug", "ghost"],
    },
    {
        id: 293,
        name: "whismur",
        koreanName: "소곤룡",
        imageUrl: "293.png",
        types: ["normal"],
    },
    {
        id: 294,
        name: "loudred",
        koreanName: "노공룡",
        imageUrl: "294.png",
        types: ["normal"],
    },
    {
        id: 295,
        name: "exploud",
        koreanName: "폭음룡",
        imageUrl: "295.png",
        types: ["normal"],
    },
    {
        id: 296,
        name: "makuhita",
        koreanName: "마크탕",
        imageUrl: "296.png",
        types: ["fighting"],
    },
    {
        id: 297,
        name: "hariyama",
        koreanName: "하리뭉",
        imageUrl: "297.png",
        types: ["fighting"],
    },
    {
        id: 298,
        name: "azurill",
        koreanName: "토오",
        imageUrl: "980.png",
        types: ["poison", "ground"],
    },
    {
        id: 299,
        name: "nosepass",
        koreanName: "코코파스",
        imageUrl: "299.png",
        types: ["rock"],
    },
    {
        id: 300,
        name: "skitty",
        koreanName: "위대한엄니",
        imageUrl: "984.png",
        types: ["ground", "fighting"],
    },
    {
        id: 301,
        name: "delcatty",
        koreanName: "무쇠바퀴",
        imageUrl: "990.png",
        types: ["ground", "steel"],
    },
    {
        id: 302,
        name: "sableye",
        koreanName: "깜까미",
        imageUrl: "302.png",
        types: ["dark", "ghost"],
    },
    {
        id: 303,
        name: "mawile",
        koreanName: "입치트",
        imageUrl: "303.png",
        types: ["steel", "fairy"],
    },
    {
        id: 304,
        name: "aron",
        koreanName: "가보리",
        imageUrl: "304.png",
        types: ["steel", "rock"],
    },
    {
        id: 305,
        name: "lairon",
        koreanName: "갱도라",
        imageUrl: "305.png",
        types: ["steel", "rock"],
    },
    {
        id: 306,
        name: "aggron",
        koreanName: "보스로라",
        imageUrl: "306.png",
        types: ["steel", "rock"],
    },
    {
        id: 307,
        name: "meditite",
        koreanName: "요가랑",
        imageUrl: "307.png",
        types: ["fighting", "psychic"],
    },
    {
        id: 308,
        name: "medicham",
        koreanName: "요가램",
        imageUrl: "308.png",
        types: ["fighting", "psychic"],
    },
    {
        id: 309,
        name: "electrike",
        koreanName: "썬더라이",
        imageUrl: "309.png",
        types: ["electric"],
    },
    {
        id: 310,
        name: "manectric",
        koreanName: "썬더볼트",
        imageUrl: "310.png",
        types: ["electric"],
    },
    {
        id: 311,
        name: "plusle",
        koreanName: "플러시",
        imageUrl: "311.png",
        types: ["electric", "fairy"],
    },
    {
        id: 312,
        name: "minun",
        koreanName: "마이농",
        imageUrl: "312.png",
        types: ["electric", "fairy"],
    },
    {
        id: 313,
        name: "volbeat",
        koreanName: "태우지네",
        imageUrl: "850.png",
        types: ["fire", "bug"],
    },
    {
        id: 314,
        name: "illumise",
        koreanName: "다태우지네",
        imageUrl: "851.png",
        types: ["fire", "bug"],
    },
    {
        id: 315,
        name: "roselia",
        koreanName: "로젤리아",
        imageUrl: "315.png",
        types: ["grass", "poison"],
    },
    {
        id: 316,
        name: "gulpin",
        koreanName: "부르롱",
        imageUrl: "965.png",
        types: ["steel", "poison"],
    },
    {
        id: 317,
        name: "swalot",
        koreanName: "부르르룸",
        imageUrl: "966.png",
        types: ["steel", "poison"],
    },
    {
        id: 318,
        name: "carvanha",
        koreanName: "샤프니아",
        imageUrl: "318.png",
        types: ["water", "dark"],
    },
    {
        id: 319,
        name: "sharpedo",
        koreanName: "샤크니아",
        imageUrl: "319.png",
        types: ["water", "dark"],
    },
    {
        id: 320,
        name: "wailmer",
        koreanName: "고래왕자",
        imageUrl: "320.png",
        types: ["water"],
    },
    {
        id: 321,
        name: "wailord",
        koreanName: "고래왕",
        imageUrl: "321.png",
        types: ["water"],
    },
    {
        id: 322,
        name: "numel",
        koreanName: "둔타",
        imageUrl: "322.png",
        types: ["fire", "ground"],
    },
    {
        id: 323,
        name: "camerupt",
        koreanName: "폭타",
        imageUrl: "323.png",
        types: ["fire", "ground"],
    },
    {
        id: 324,
        name: "torkoal",
        koreanName: "코터스",
        imageUrl: "324.png",
        types: ["fire"],
    },
    {
        id: 325,
        name: "spoink",
        koreanName: "짜랑꼬",
        imageUrl: "782.png",
        types: ["dragon"],
    },
    {
        id: 326,
        name: "grumpig",
        koreanName: "짜랑고우",
        imageUrl: "783.png",
        types: ["dragon", "fighting"],
    },
    {
        id: 327,
        name: "spinda",
        koreanName: "짜랑고우거",
        imageUrl: "784.png",
        types: ["dragon", "fighting"],
    },
    {
        id: 328,
        name: "trapinch",
        koreanName: "톱치",
        imageUrl: "328.png",
        types: ["bug", "ground"],
    },
    {
        id: 329,
        name: "vibrava",
        koreanName: "비브라바",
        imageUrl: "329.png",
        types: ["bug", "dragon"],
    },
    {
        id: 330,
        name: "flygon",
        koreanName: "플라이곤",
        imageUrl: "330.png",
        types: ["bug", "dragon"],
    },
    {
        id: 331,
        name: "cacnea",
        koreanName: "모으령",
        imageUrl: "999.png",
        types: ["ghost"],
    },
    {
        id: 332,
        name: "cacturne",
        koreanName: "타부자고",
        imageUrl: "1000.png",
        types: ["steel", "ghost"],
    },
    {
        id: 333,
        name: "swablu",
        koreanName: "파비코",
        imageUrl: "333.png",
        types: ["fairy", "flying"],
    },
    {
        id: 334,
        name: "altaria",
        koreanName: "파비코리",
        imageUrl: "334.png",
        types: ["dragon", "fairy"],
    },
    {
        id: 335,
        name: "zangoose",
        koreanName: "쟝고",
        imageUrl: "335.png",
        types: ["normal"],
    },
    {
        id: 336,
        name: "seviper",
        koreanName: "세비퍼",
        imageUrl: "336.png",
        types: ["poison"],
    },
    {
        id: 337,
        name: "lunatone",
        koreanName: "루나톤",
        imageUrl: "337.png",
        types: ["rock", "psychic"],
    },
    {
        id: 338,
        name: "solrock",
        koreanName: "솔록",
        imageUrl: "338.png",
        types: ["rock", "psychic"],
    },
    {
        id: 339,
        name: "barboach",
        koreanName: "미꾸리",
        imageUrl: "339.png",
        types: ["water", "ground"],
    },
    {
        id: 340,
        name: "whiscash",
        koreanName: "메깅",
        imageUrl: "340.png",
        types: ["water", "ground"],
    },
    {
        id: 341,
        name: "corphish",
        koreanName: "가재군",
        imageUrl: "341.png",
        types: ["water"],
    },
    {
        id: 342,
        name: "crawdaunt",
        koreanName: "가재장군",
        imageUrl: "342.png",
        types: ["water", "dark"],
    },
    {
        id: 343,
        name: "baltoy",
        koreanName: "오뚝군",
        imageUrl: "343.png",
        types: ["ground", "psychic"],
    },
    {
        id: 344,
        name: "claydol",
        koreanName: "점토도리",
        imageUrl: "344.png",
        types: ["ground", "psychic"],
    },
    {
        id: 345,
        name: "lileep",
        koreanName: "릴링",
        imageUrl: "345.png",
        types: ["rock", "grass"],
    },
    {
        id: 346,
        name: "cradily",
        koreanName: "릴리요",
        imageUrl: "346.png",
        types: ["rock", "grass"],
    },
    {
        id: 347,
        name: "anorith",
        koreanName: "아노딥스",
        imageUrl: "347.png",
        types: ["rock", "bug"],
    },
    {
        id: 348,
        name: "armaldo",
        koreanName: "아말도",
        imageUrl: "348.png",
        types: ["rock", "bug"],
    },
    {
        id: 349,
        name: "feebas",
        koreanName: "빈티나",
        imageUrl: "349.png",
        types: ["water"],
    },
    {
        id: 350,
        name: "milotic",
        koreanName: "밀로틱",
        imageUrl: "350.png",
        types: ["water"],
    },
    {
        id: 351,
        name: "castform",
        koreanName: "캐스퐁",
        form: [
            {
                formName: "노말",
                imageUrl: "351.png",
                types: ["normal"],
            },
            {
                formName: "태양",
                imageUrl: "10013.png",
                types: ["fire", "grass"],
            },
            {
                formName: "빗방울",
                imageUrl: "10014.png",
                types: ["water", "flying"],
            },
            {
                formName: "설운",
                imageUrl: "10015.png",
                types: ["ice", "electric"],
            },
        ],
    },
    {
        id: 352,
        name: "kecleon",
        koreanName: "저승갓숭",
        imageUrl: "979.png",
        types: ["fighting", "ghost"],
    },
    {
        id: 353,
        name: "shuppet",
        koreanName: "어둠대신",
        imageUrl: "353.png",
        types: ["ghost"],
    },
    {
        id: 354,
        name: "banette",
        koreanName: "다크펫",
        imageUrl: "354.png",
        types: ["ghost", "normal"],
    },
    {
        id: 355,
        name: "duskull",
        koreanName: "해골몽",
        imageUrl: "355.png",
        types: ["ghost"],
    },
    {
        id: 356,
        name: "dusclops",
        koreanName: "미라몽",
        imageUrl: "356.png",
        types: ["ghost"],
    },
    {
        id: 357,
        name: "tropius",
        koreanName: "트로피우스",
        imageUrl: "357.png",
        types: ["grass", "flying"],
    },
    {
        id: 358,
        name: "chimecho",
        koreanName: "치렁",
        imageUrl: "358.png",
        types: ["psychic"],
    },
    {
        id: 359,
        name: "absol",
        koreanName: "앱솔",
        imageUrl: "359.png",
        types: ["dark"],
    },
    {
        id: 360,
        name: "wynaut",
        koreanName: "무쇠가시",
        imageUrl: "995.png",
        types: ["rock", "electric"],
    },
    {
        id: 361,
        name: "snorunt",
        koreanName: "눈꼬마",
        imageUrl: "361.png",
        types: ["ice"],
    },
    {
        id: 362,
        name: "glalie",
        koreanName: "얼음귀신",
        imageUrl: "362.png",
        types: ["ice"],
    },
    {
        id: 363,
        name: "spheal",
        koreanName: "드니차",
        imageUrl: "996.png",
        types: ["dragon", "ice"],
    },
    {
        id: 364,
        name: "sealeo",
        koreanName: "드니꽁",
        imageUrl: "997.png",
        types: ["dragon", "ice"],
    },
    {
        id: 365,
        name: "walrein",
        koreanName: "드닐레이브",
        imageUrl: "998.png",
        types: ["dragon", "ice"],
    },
    {
        id: 366,
        name: "clamperl",
        koreanName: "카르본",
        imageUrl: "935.png",
        types: ["fire"],
    },
    {
        id: 367,
        name: "huntail",
        koreanName: "카디나르마",
        imageUrl: "936.png",
        types: ["fire", "psychic"],
    },
    {
        id: 368,
        name: "gorebyss",
        koreanName: "파라블레이즈",
        imageUrl: "937.png",
        types: ["fire", "ghost"],
    },
    {
        id: 369,
        name: "relicanth",
        koreanName: "오기지게",
        imageUrl: "739.png",
        types: ["fighting"],
    },
    {
        id: 370,
        name: "luvdisc",
        koreanName: "모단단게",
        imageUrl: "740.png",
        types: ["fighting", "ice"],
    },
    {
        id: 371,
        name: "bagon",
        koreanName: "아공이",
        imageUrl: "371.png",
        types: ["dragon"],
    },
    {
        id: 372,
        name: "shelgon",
        koreanName: "쉘곤",
        imageUrl: "372.png",
        types: ["dragon"],
    },
    {
        id: 373,
        name: "salamence",
        koreanName: "보만다",
        imageUrl: "373.png",
        types: ["dragon", "flying"],
    },
    {
        id: 374,
        name: "beldum",
        koreanName: "메탕",
        imageUrl: "374.png",
        types: ["steel", "psychic"],
    },
    {
        id: 375,
        name: "metang",
        koreanName: "메탕구",
        imageUrl: "375.png",
        types: ["steel", "psychic"],
    },
    {
        id: 376,
        name: "metagross",
        koreanName: "메타그로스",
        imageUrl: "376.png",
        types: ["steel", "psychic"],
    },
    {
        id: 377,
        name: "regirock",
        koreanName: "레지락",
        imageUrl: "377.png",
        types: ["rock"],
    },
    {
        id: 378,
        name: "regice",
        koreanName: "레지아이스",
        imageUrl: "378.png",
        types: ["ice"],
    },
    {
        id: 379,
        name: "registeel",
        koreanName: "레지스틸",
        imageUrl: "379.png",
        types: ["steel"],
    },
    {
        id: 380,
        name: "latias",
        koreanName: "라티아스",
        imageUrl: "380.png",
        types: ["dragon", "psychic"],
    },
    {
        id: 381,
        name: "latios",
        koreanName: "라티오스",
        imageUrl: "381.png",
        types: ["dragon", "psychic"],
    },
    {
        id: 382,
        name: "kyogre",
        koreanName: "가이오가",
        imageUrl: "382.png",
        types: ["water"],
    },
    {
        id: 383,
        name: "groudon",
        koreanName: "그란돈",
        imageUrl: "383.png",
        types: ["ground"],
    },
    {
        id: 384,
        name: "rayquaza",
        koreanName: "레쿠쟈",
        imageUrl: "384.png",
        types: ["dragon", "flying"],
    },
    {
        id: 385,
        name: "jirachi",
        koreanName: "지라치",
        imageUrl: "385.png",
        types: ["steel", "psychic"],
    },
    {
        id: 386,
        name: "deoxys-normal",
        koreanName: "테오키스",
        form: [
            {
                formName: "노말",
                imageUrl: "386.png",
                types: ["psychic"],
            },
            {
                formName: "어택",
                imageUrl: "10001.png",
                types: ["psychic"],
            },
            {
                formName: "디펜스",
                imageUrl: "10002.png",
                types: ["psychic"],
            },
            {
                formName: "스피드",
                imageUrl: "10003.png",
                types: ["psychic"],
            },
        ],
    },
    {
        id: 387,
        name: "turtwig",
        koreanName: "모부기",
        imageUrl: "387.png",
        types: ["grass"],
    },
    {
        id: 388,
        name: "grotle",
        koreanName: "수풀부기",
        imageUrl: "388.png",
        types: ["grass"],
    },
    {
        id: 389,
        name: "torterra",
        koreanName: "토대부기",
        imageUrl: "389.png",
        types: ["grass", "ground"],
    },
    {
        id: 390,
        name: "chimchar",
        koreanName: "불꽃숭이",
        imageUrl: "390.png",
        types: ["fire"],
    },
    {
        id: 391,
        name: "monferno",
        koreanName: "파이숭이",
        imageUrl: "391.png",
        types: ["fire", "fighting"],
    },
    {
        id: 392,
        name: "infernape",
        koreanName: "초염몽",
        imageUrl: "392.png",
        types: ["fire", "fighting"],
    },
    {
        id: 393,
        name: "piplup",
        koreanName: "팽도리",
        imageUrl: "393.png",
        types: ["water"],
    },
    {
        id: 394,
        name: "prinplup",
        koreanName: "팽태자",
        imageUrl: "394.png",
        types: ["water"],
    },
    {
        id: 395,
        name: "empoleon",
        koreanName: "엠페르트",
        imageUrl: "395.png",
        types: ["water", "steel"],
    },
    {
        id: 396,
        name: "starly",
        koreanName: "찌르꼬",
        imageUrl: "396.png",
        types: ["normal", "flying"],
    },
    {
        id: 397,
        name: "staravia",
        koreanName: "찌르버드",
        imageUrl: "397.png",
        types: ["normal", "flying"],
    },
    {
        id: 398,
        name: "staraptor",
        koreanName: "찌르호크",
        imageUrl: "398.png",
        types: ["normal", "flying"],
    },
    {
        id: 399,
        name: "bidoof",
        koreanName: "비버니",
        imageUrl: "399.png",
        types: ["normal"],
    },
    {
        id: 400,
        name: "bibarel",
        koreanName: "비버통",
        imageUrl: "400.png",
        types: ["normal", "water"],
    },
    {
        id: 401,
        name: "kricketot",
        koreanName: "콩알뚜기",
        imageUrl: "919.png",
        types: ["bug"],
    },
    {
        id: 402,
        name: "kricketune",
        koreanName: "엑스레그",
        imageUrl: "920.png",
        types: ["bug", "dark"],
    },
    {
        id: 403,
        name: "shinx",
        koreanName: "꼬링크",
        imageUrl: "403.png",
        types: ["electric"],
    },
    {
        id: 404,
        name: "luxio",
        koreanName: "럭시오",
        imageUrl: "404.png",
        types: ["electric"],
    },
    {
        id: 405,
        name: "luxray",
        koreanName: "렌트라",
        imageUrl: "405.png",
        types: ["electric", "dark"],
    },
    {
        id: 406,
        name: "budew",
        koreanName: "윈디(히스이)",
        imageUrl: "10230.png",
        types: ["fire", "rock"],
    },
    {
        id: 407,
        name: "roserade",
        koreanName: "로즈레이드",
        imageUrl: "407.png",
        types: ["grass", "poison"],
    },
    {
        id: 408,
        name: "cranidos",
        koreanName: "티고라스",
        imageUrl: "696.png",
        types: ["rock", "dragon"],
    },
    {
        id: 409,
        name: "rampardos",
        koreanName: "견고라스",
        imageUrl: "697.png",
        types: ["rock", "dragon"],
    },
    {
        id: 410,
        name: "shieldon",
        koreanName: "아마루스",
        imageUrl: "698.png",
        types: ["rock", "ice"],
    },
    {
        id: 411,
        name: "bastiodon",
        koreanName: "아마루르가",
        imageUrl: "699.png",
        types: ["rock", "ice"],
    },
    {
        id: 412,
        name: "burmy",
        koreanName: "암멍이",
        imageUrl: "744.png",
        types: ["rock"],
    },
    {
        id: 413,
        name: "wormadam-plant",
        koreanName: "루가루암",
        form: [
            {
                formName: "한낮",
                imageUrl: "745.png",
                types: ["rock", "dark"],
            },
            {
                formName: "한밤중",
                imageUrl: "10126.png",
                types: ["rock", "ghost"],
            },
            {
                formName: "황혼",
                imageUrl: "10152.png",
                types: ["rock", "fighting"],
            },
        ],
    },
    {
        id: 414,
        name: "mothim",
        koreanName: "장침바루",
        imageUrl: "904.png",
        types: ["dark", "poison"],
    },
    {
        id: 415,
        name: "combee",
        koreanName: "메롱꿍",
        imageUrl: "859.png",
        types: ["dark", "fairy"],
    },
    {
        id: 416,
        name: "vespiquen",
        koreanName: "쏘겨모",
        imageUrl: "860.png",
        types: ["dark", "fairy"],
    },
    {
        id: 417,
        name: "pachirisu",
        koreanName: "오롱털",
        imageUrl: "861.png",
        types: ["dark", "fairy"],
    },
    {
        id: 418,
        name: "buizel",
        koreanName: "찌로꼬치",
        imageUrl: "846.png",
        types: ["water"],
    },
    {
        id: 419,
        name: "floatzel",
        koreanName: "꼬치조",
        imageUrl: "847.png",
        types: ["water"],
    },
    {
        id: 420,
        name: "cherubi",
        koreanName: "체리버",
        imageUrl: "420.png",
        types: ["grass"],
    },
    {
        id: 421,
        name: "cherrim",
        koreanName: "체리꼬",
        imageUrl: "421.png",
        types: ["grass"],
    },
    {
        id: 422,
        name: "shellos",
        koreanName: "일레즌",
        imageUrl: "848.png",
        types: ["electric", "poison"],
    },
    {
        id: 423,
        name: "gastrodon",
        koreanName: "스트린더",
        form: [
            {
                formName: "하이폼",
                imageUrl: "849.png",
                types: ["electric", "poison"],
            },
            {
                formName: "로우폼",
                imageUrl: "10184.png",
                types: ["electric", "poison"],
            },
        ],
    },
    {
        id: 424,
        name: "ambipom",
        koreanName: "겟핸보숭",
        imageUrl: "424.png",
        types: ["normal"],
    },
    {
        id: 425,
        name: "drifloon",
        koreanName: "흔들풍손",
        imageUrl: "425.png",
        types: ["ghost", "flying"],
    },
    {
        id: 426,
        name: "drifblim",
        koreanName: "둥실라이드",
        imageUrl: "426.png",
        types: ["ghost", "flying"],
    },
    {
        id: 427,
        name: "buneary",
        koreanName: "이어롤",
        imageUrl: "427.png",
        types: ["normal"],
    },
    {
        id: 428,
        name: "lopunny",
        koreanName: "이어롭",
        imageUrl: "428.png",
        types: ["normal", "fighting"],
    },
    {
        id: 429,
        name: "mismagius",
        koreanName: "무우마직",
        imageUrl: "429.png",
        types: ["ghost", "dark"],
    },
    {
        id: 430,
        name: "honchkrow",
        koreanName: "돈크로우",
        imageUrl: "430.png",
        types: ["dark", "flying"],
    },
    {
        id: 431,
        name: "glameow",
        koreanName: "꽁어름",
        imageUrl: "712.png",
        types: ["ice"],
    },
    {
        id: 432,
        name: "purugly",
        koreanName: "크레베이스",
        imageUrl: "713.png",
        types: ["ice", "steel"],
    },
    {
        id: 433,
        name: "chingling",
        koreanName: "멜리시",
        imageUrl: "703.png",
        types: ["rock", "fairy"],
    },
    {
        id: 434,
        name: "stunky",
        koreanName: "모래꿍",
        imageUrl: "769.png",
        types: ["ghost", "ground"],
    },
    {
        id: 435,
        name: "skuntank",
        koreanName: "모래성이당",
        imageUrl: "771.png",
        types: ["ghost", "ground"],
    },
    {
        id: 436,
        name: "bronzor",
        koreanName: "동미러",
        imageUrl: "436.png",
        types: ["steel", "psychic"],
    },
    {
        id: 437,
        name: "bronzong",
        koreanName: "동탁군",
        imageUrl: "437.png",
        types: ["steel", "psychic"],
    },
    {
        id: 438,
        name: "bonsly",
        koreanName: "모크나이퍼(히스이)",
        imageUrl: "10244.png",
        types: ["grass", "fighting"],
    },
    {
        id: 439,
        name: "mime-jr",
        koreanName: "블레이범(히스이)",
        imageUrl: "10233.png",
        types: ["fire", "ghost"],
    },
    {
        id: 440,
        name: "happiny",
        koreanName: "대검귀(히스이)",
        imageUrl: "10236.png",
        types: ["water", "dark"],
    },
    {
        id: 441,
        name: "chatot",
        koreanName: "페라페",
        imageUrl: "441.png",
        types: ["normal", "flying"],
    },
    {
        id: 442,
        name: "spiritomb",
        koreanName: "화강돌",
        imageUrl: "442.png",
        types: ["ghost", "dark"],
    },
    {
        id: 443,
        name: "gible",
        koreanName: "딥상어동",
        imageUrl: "443.png",
        types: ["dragon", "ground"],
    },
    {
        id: 444,
        name: "gabite",
        koreanName: "한바이트",
        imageUrl: "444.png",
        types: ["dragon", "ground"],
    },
    {
        id: 445,
        name: "garchomp",
        koreanName: "한카리아스",
        imageUrl: "445.png",
        types: ["dragon", "ground"],
    },
    {
        id: 446,
        name: "munchlax",
        koreanName: "볼케니온",
        imageUrl: "721.png",
        types: ["fire", "water"],
    },
    {
        id: 447,
        name: "riolu",
        koreanName: "리오르",
        imageUrl: "447.png",
        types: ["fighting"],
    },
    {
        id: 448,
        name: "lucario",
        koreanName: "루카리오",
        imageUrl: "448.png",
        types: ["fighting", "steel"],
    },
    {
        id: 449,
        name: "hippopotas",
        koreanName: "히포포타스",
        imageUrl: "449.png",
        types: ["ground"],
    },
    {
        id: 450,
        name: "hippowdon",
        koreanName: "하마돈",
        imageUrl: "450.png",
        types: ["ground"],
    },
    {
        id: 451,
        name: "skorupi",
        koreanName: "스콜피",
        imageUrl: "451.png",
        types: ["poison", "bug"],
    },
    {
        id: 452,
        name: "drapion",
        koreanName: "드래피온",
        imageUrl: "452.png",
        types: ["poison", "dark"],
    },
    {
        id: 453,
        name: "croagunk",
        koreanName: "삐딱구리",
        imageUrl: "453.png",
        types: ["poison", "fighting"],
    },
    {
        id: 454,
        name: "toxicroak",
        koreanName: "독개굴",
        imageUrl: "454.png",
        types: ["poison", "fighting"],
    },
    {
        id: 455,
        name: "carnivine",
        koreanName: "포푸니크",
        imageUrl: "903.png",
        types: ["fighting", "poison"],
    },
    {
        id: 456,
        name: "finneon",
        koreanName: "형광어",
        imageUrl: "456.png",
        types: ["water", "fairy"],
    },
    {
        id: 457,
        name: "lumineon",
        koreanName: "네오라이트",
        imageUrl: "457.png",
        types: ["water", "fairy"],
    },
    {
        id: 458,
        name: "mantyke",
        koreanName: "무쇠손",
        imageUrl: "992.png",
        types: ["fighting", "electric"],
    },
    {
        id: 459,
        name: "snover",
        koreanName: "눈쓰개",
        imageUrl: "459.png",
        types: ["grass", "ice"],
    },
    {
        id: 460,
        name: "abomasnow",
        koreanName: "눈설왕",
        imageUrl: "460.png",
        types: ["grass", "ice"],
    },
    {
        id: 461,
        name: "weavile",
        koreanName: "포푸니라",
        imageUrl: "461.png",
        types: ["dark", "ice"],
    },
    {
        id: 462,
        name: "magnezone",
        koreanName: "자포코일",
        imageUrl: "462.png",
        types: ["electric", "steel"],
    },
    {
        id: 463,
        name: "lickilicky",
        koreanName: "내룸벨트",
        imageUrl: "463.png",
        types: ["normal"],
    },
    {
        id: 464,
        name: "rhyperior",
        koreanName: "거대코뿌리",
        imageUrl: "464.png",
        types: ["ground", "rock"],
    },
    {
        id: 465,
        name: "tangrowth",
        koreanName: "덩쿠림보",
        imageUrl: "465.png",
        types: ["grass", "ghost"],
    },
    {
        id: 466,
        name: "electivire",
        koreanName: "에레키블",
        imageUrl: "466.png",
        types: ["electric", "fighting"],
    },
    {
        id: 467,
        name: "magmortar",
        koreanName: "마그마번",
        imageUrl: "467.png",
        types: ["fire"],
    },
    {
        id: 468,
        name: "togekiss",
        koreanName: "토게키스",
        imageUrl: "468.png",
        types: ["fairy", "flying"],
    },
    {
        id: 469,
        name: "yanmega",
        koreanName: "메가자리",
        imageUrl: "469.png",
        types: ["bug", "flying"],
    },
    {
        id: 470,
        name: "leafeon",
        koreanName: "리피아",
        imageUrl: "470.png",
        types: ["grass"],
    },
    {
        id: 471,
        name: "glaceon",
        koreanName: "글레이시아",
        imageUrl: "471.png",
        types: ["ice"],
    },
    {
        id: 472,
        name: "gliscor",
        koreanName: "글라이온",
        imageUrl: "472.png",
        types: ["ground", "flying"],
    },
    {
        id: 473,
        name: "mamoswine",
        koreanName: "맘모꾸리",
        imageUrl: "473.png",
        types: ["ice", "ground"],
    },
    {
        id: 474,
        name: "porygon-z",
        koreanName: "폴리곤Z",
        imageUrl: "474.png",
        types: ["normal"],
    },
    {
        id: 475,
        name: "gallade",
        koreanName: "엘레이드",
        imageUrl: "475.png",
        types: ["psychic", "fighting"],
    },
    {
        id: 476,
        name: "probopass",
        koreanName: "대코파스",
        imageUrl: "476.png",
        types: ["rock", "electric"],
    },
    {
        id: 477,
        name: "dusknoir",
        koreanName: "야느와르몽",
        imageUrl: "477.png",
        types: ["ghost"],
    },
    {
        id: 478,
        name: "froslass",
        koreanName: "눈여아",
        imageUrl: "478.png",
        types: ["ice", "ghost"],
    },
    {
        id: 479,
        name: "rotom",
        koreanName: "로토무",
        form: [
            {
                formName: "일반",
                imageUrl: "479.png",
                types: ["electric", "ghost"],
            },
            {
                formName: "히트",
                imageUrl: "10008.png",
                types: ["electric", "fire"],
            },
            {
                formName: "워시",
                imageUrl: "10009.png",
                types: ["electric", "water"],
            },
            {
                formName: "프로스트",
                imageUrl: "10010.png",
                types: ["electric", "ice"],
            },
            {
                formName: "스핀",
                imageUrl: "10011.png",
                types: ["electric", "flying"],
            },
            {
                formName: "커트",
                imageUrl: "10012.png",
                types: ["electric", "grass"],
            },
        ],
    },
    {
        id: 480,
        name: "uxie",
        koreanName: "유크시",
        imageUrl: "480.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 481,
        name: "mesprit",
        koreanName: "엠라이트",
        imageUrl: "481.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 482,
        name: "azelf",
        koreanName: "아그놈",
        imageUrl: "482.png",
        types: ["psychic", "fairy"],
    },
    {
        id: 483,
        name: "dialga",
        koreanName: "디아루가",
        imageUrl: "483.png",
        types: ["steel", "dragon"],
    },
    {
        id: 484,
        name: "palkia",
        koreanName: "펄기아",
        imageUrl: "484.png",
        types: ["water", "dragon"],
    },
    {
        id: 485,
        name: "heatran",
        koreanName: "히드런",
        imageUrl: "485.png",
        types: ["fire", "steel"],
    },
    {
        id: 486,
        name: "regigigas",
        koreanName: "레지기가스",
        imageUrl: "486.png",
        types: ["normal"],
    },
    {
        id: 487,
        name: "giratina-altered",
        koreanName: "기라티나",
        form: [
            {
                formName: "어나더",
                imageUrl: "487.png",
                types: ["ghost", "dragon"],
            },
            {
                formName: "오리진",
                imageUrl: "10007.png",
                types: ["ghost", "dragon"],
            },
        ]
    },
    {
        id: 488,
        name: "cresselia",
        koreanName: "크레세리아",
        imageUrl: "488.png",
        types: ["psychic"],
    },
    {
        id: 489,
        name: "phione",
        koreanName: "디안시",
        imageUrl: "719.png",
        types: ["rock", "fairy"],
    },
    {
        id: 490,
        name: "manaphy",
        koreanName: "마나피",
        imageUrl: "490.png",
        types: ["water", "fairy"],
    },
    {
        id: 491,
        name: "darkrai",
        koreanName: "다크라이",
        imageUrl: "491.png",
        types: ["dark"],
    },
    {
        id: 492,
        name: "shaymin-land",
        koreanName: "쉐이미",
        form: [
            {
                formName: "랜드",
                imageUrl: "492.png",
                types: ["grass"],
            },
            {
                formName: "스카이",
                imageUrl: "10006.png",
                types: ["grass", "flying"],
            },
        ]
    },
    {
        id: 493,
        name: "arceus",
        koreanName: "아르세우스",
        imageUrl: "493.png",
        types: ["normal"],
    },
    {
        id: 494,
        name: "victini",
        koreanName: "비크티니",
        imageUrl: "494.png",
        types: ["psychic", "fire"],
    },
    {
        id: 495,
        name: "snivy",
        koreanName: "주리비얀",
        imageUrl: "495.png",
        types: ["grass"],
    },
    {
        id: 496,
        name: "servine",
        koreanName: "샤비",
        imageUrl: "496.png",
        types: ["grass", "dragon"],
    },
    {
        id: 497,
        name: "serperior",
        koreanName: "샤로다",
        imageUrl: "497.png",
        types: ["grass", "dragon"],
    },
    {
        id: 498,
        name: "tepig",
        koreanName: "뚜꾸리",
        imageUrl: "498.png",
        types: ["fire"],
    },
    {
        id: 499,
        name: "pignite",
        koreanName: "차오꿀",
        imageUrl: "499.png",
        types: ["fire", "ground"],
    },
    {
        id: 500,
        name: "emboar",
        koreanName: "염무왕",
        imageUrl: "500.png",
        types: ["fire", "ground"],
    },
    {
        id: 501,
        name: "oshawott",
        koreanName: "수댕이",
        imageUrl: "501.png",
        types: ["water"],
    },
    {
        id: 502,
        name: "dewott",
        koreanName: "쌍검자비",
        imageUrl: "502.png",
        types: ["water"],
    },
    {
        id: 503,
        name: "samurott",
        koreanName: "대검귀",
        imageUrl: "503.png",
        types: ["water", "fighting"],
    },
    {
        id: 504,
        name: "patrat",
        koreanName: "에블리",
        imageUrl: "742.png",
        types: ["bug", "fairy"],
    },
    {
        id: 505,
        name: "watchog",
        koreanName: "에리본",
        imageUrl: "743.png",
        types: ["bug", "fairy"],
    },
    {
        id: 506,
        name: "lillipup",
        koreanName: "요테리",
        imageUrl: "506.png",
        types: ["normal"],
    },
    {
        id: 507,
        name: "herdier",
        koreanName: "하데리어",
        imageUrl: "507.png",
        types: ["normal"],
    },
    {
        id: 508,
        name: "stoutland",
        koreanName: "바랜드",
        imageUrl: "508.png",
        types: ["normal"],
    },
    {
        id: 509,
        name: "purrloin",
        koreanName: "쌔비냥",
        imageUrl: "509.png",
        types: ["dark"],
    },
    {
        id: 510,
        name: "liepard",
        koreanName: "레파르다스",
        imageUrl: "510.png",
        types: ["dark"],
    },
    {
        id: 511,
        name: "pansage",
        koreanName: "미끄메라",
        imageUrl: "704.png",
        types: ["dragon"],
    },
    {
        id: 512,
        name: "simisage",
        koreanName: "미끄네일",
        imageUrl: "705.png",
        types: ["dragon"],
    },
    {
        id: 513,
        name: "pansear",
        koreanName: "미끄래곤",
        imageUrl: "706.png",
        types: ["dragon"],
    },
    {
        id: 514,
        name: "simisear",
        koreanName: "턱지충이",
        imageUrl: "736.png",
        types: ["bug"],
    },
    {
        id: 515,
        name: "panpour",
        koreanName: "전지충이",
        imageUrl: "737.png",
        types: ["bug", "electric"],
    },
    {
        id: 516,
        name: "simipour",
        koreanName: "투구뿌논",
        imageUrl: "738.png",
        types: ["bug", "electric"],
    },
    {
        id: 517,
        name: "munna",
        koreanName: "두랄루돈",
        imageUrl: "884.png",
        types: ["steel", "dragon"],
    },
    {
        id: 518,
        name: "musharna",
        koreanName: "브리두라스",
        imageUrl: "1018.png",
        types: ["steel", "dragon"],
    },
    {
        id: 519,
        name: "pidove",
        koreanName: "화살꼬빈",
        imageUrl: "661.png",
        types: ["normal", "flying"],
    },
    {
        id: 520,
        name: "tranquill",
        koreanName: "불화살빈",
        imageUrl: "662.png",
        types: ["fire", "flying"],
    },
    {
        id: 521,
        name: "unfezant",
        koreanName: "파이어로",
        imageUrl: "663.png",
        types: ["fire", "flying"],
    },
    {
        id: 522,
        name: "blitzle",
        koreanName: "줄뮤마",
        imageUrl: "522.png",
        types: ["electric"],
    },
    {
        id: 523,
        name: "zebstrika",
        koreanName: "제브라이카",
        imageUrl: "523.png",
        types: ["electric"],
    },
    {
        id: 524,
        name: "roggenrola",
        koreanName: "단굴",
        imageUrl: "524.png",
        types: ["rock"],
    },
    {
        id: 525,
        name: "boldore",
        koreanName: "암트르",
        imageUrl: "525.png",
        types: ["rock"],
    },
    {
        id: 526,
        name: "gigalith",
        koreanName: "기가이어스",
        imageUrl: "526.png",
        types: ["rock"],
    },
    {
        id: 527,
        name: "woobat",
        koreanName: "또르박쥐",
        imageUrl: "527.png",
        types: ["psychic", "flying"],
    },
    {
        id: 528,
        name: "swoobat",
        koreanName: "맘박쥐",
        imageUrl: "528.png",
        types: ["psychic", "flying"],
    },
    {
        id: 529,
        name: "drilbur",
        koreanName: "두더류",
        imageUrl: "529.png",
        types: ["ground"],
    },
    {
        id: 530,
        name: "excadrill",
        koreanName: "몰드류",
        imageUrl: "530.png",
        types: ["ground", "steel"],
    },
    {
        id: 531,
        name: "audino",
        koreanName: "다부니",
        imageUrl: "531.png",
        types: ["normal", "fairy"],
    },
    {
        id: 532,
        name: "timburr",
        koreanName: "으랏차",
        imageUrl: "532.png",
        types: ["fighting"],
    },
    {
        id: 533,
        name: "gurdurr",
        koreanName: "토쇠골",
        imageUrl: "533.png",
        types: ["fighting"],
    },
    {
        id: 534,
        name: "conkeldurr",
        koreanName: "노보청",
        imageUrl: "534.png",
        types: ["fighting"],
    },
    {
        id: 535,
        name: "tympole",
        koreanName: "동챙이",
        imageUrl: "535.png",
        types: ["water"],
    },
    {
        id: 536,
        name: "palpitoad",
        koreanName: "두까비",
        imageUrl: "536.png",
        types: ["water", "ground"],
    },
    {
        id: 537,
        name: "seismitoad",
        koreanName: "두빅굴",
        imageUrl: "537.png",
        types: ["water", "ground"],
    },
    {
        id: 538,
        name: "throh",
        koreanName: "땅을기는날개",
        imageUrl: "988.png",
        types: ["bug", "fighting"],
    },
    {
        id: 539,
        name: "sawk",
        koreanName: "무쇠독나방",
        imageUrl: "994.png",
        types: ["fire", "poison"],
    },
    {
        id: 540,
        name: "sewaddle",
        koreanName: "두르보",
        imageUrl: "540.png",
        types: ["bug", "grass"],
    },
    {
        id: 541,
        name: "swadloon",
        koreanName: "두르쿤",
        imageUrl: "541.png",
        types: ["bug", "grass"],
    },
    {
        id: 542,
        name: "leavanny",
        koreanName: "모아머",
        imageUrl: "542.png",
        types: ["bug", "grass"],
    },
    {
        id: 543,
        name: "venipede",
        koreanName: "마디네",
        imageUrl: "543.png",
        types: ["bug", "poison"],
    },
    {
        id: 544,
        name: "whirlipede",
        koreanName: "휠구",
        imageUrl: "544.png",
        types: ["bug", "poison"],
    },
    {
        id: 545,
        name: "scolipede",
        koreanName: "펜드라",
        imageUrl: "545.png",
        types: ["bug", "poison"],
    },
    {
        id: 546,
        name: "cottonee",
        koreanName: "소미안",
        imageUrl: "546.png",
        types: ["grass", "fairy"],
    },
    {
        id: 547,
        name: "whimsicott",
        koreanName: "엘풍",
        imageUrl: "547.png",
        types: ["grass", "fairy"],
    },
    {
        id: 548,
        name: "petilil",
        koreanName: "치릴리",
        imageUrl: "548.png",
        types: ["grass"],
    },
    {
        id: 549,
        name: "lilligant",
        koreanName: "드레디어",
        imageUrl: "549.png",
        types: ["grass"],
    },
    {
        id: 550,
        name: "basculin-red-striped",
        koreanName: "대쓰여너",
        form: [
            {
                formName: "적색근",
                imageUrl: "902.png",
                types: ["water", "ghost"],
            },
            {
                formName: " 청색근",
                imageUrl: "10248.png",
                types: ["water", "ghost"],
            },
        ],
    },
    {
        id: 551,
        name: "sandile",
        koreanName: "깜눈크",
        imageUrl: "551.png",
        types: ["ground", "dark"],
    },
    {
        id: 552,
        name: "krokorok",
        koreanName: "악비르",
        imageUrl: "552.png",
        types: ["ground", "dark"],
    },
    {
        id: 553,
        name: "krookodile",
        koreanName: "악비아르",
        imageUrl: "553.png",
        types: ["ground", "dark"],
    },
    {
        id: 554,
        name: "darumaka",
        koreanName: "달막화",
        imageUrl: "554.png",
        types: ["fire"],
    },
    {
        id: 555,
        name: "darmanitan-standard",
        koreanName: "불비달마",
        form: [
            {
                formName: "노말모드",
                imageUrl: "555.png",
                types: ["fire"],
            },
            {
                formName: "달마모드",
                imageUrl: "10017.png",
                types: ["fire", "psychic"],
            },
        ]
    },
    {
        id: 556,
        name: "maractus",
        koreanName: "마라카치",
        imageUrl: "556.png",
        types: ["grass"],
    },
    {
        id: 557,
        name: "dwebble",
        koreanName: "돌살이",
        imageUrl: "557.png",
        types: ["bug", "rock"],
    },
    {
        id: 558,
        name: "crustle",
        koreanName: "암팰리스",
        imageUrl: "558.png",
        types: ["bug", "rock"],
    },
    {
        id: 559,
        name: "scraggy",
        koreanName: "곤율랭",
        imageUrl: "559.png",
        types: ["dark", "fighting"],
    },
    {
        id: 560,
        name: "scrafty",
        koreanName: "곤율거니",
        imageUrl: "560.png",
        types: ["dark", "fighting"],
    },
    {
        id: 561,
        name: "sigilyph",
        koreanName: "심보러",
        imageUrl: "561.png",
        types: ["psychic", "flying"],
    },
    {
        id: 562,
        name: "yamask",
        koreanName: "데스마스",
        imageUrl: "562.png",
        types: ["ghost"],
    },
    {
        id: 563,
        name: "cofagrigus",
        koreanName: "데스니칸",
        imageUrl: "563.png",
        types: ["ghost"],
    },
    {
        id: 564,
        name: "tirtouga",
        koreanName: "프로토가",
        imageUrl: "564.png",
        types: ["water", "rock"],
    },
    {
        id: 565,
        name: "carracosta",
        koreanName: "늑골라",
        imageUrl: "565.png",
        types: ["water", "rock"],
    },
    {
        id: 566,
        name: "archen",
        koreanName: "아켄",
        imageUrl: "566.png",
        types: ["rock", "flying"],
    },
    {
        id: 567,
        name: "archeops",
        koreanName: "아케오스",
        imageUrl: "567.png",
        types: ["rock", "flying"],
    },
    {
        id: 568,
        name: "trubbish",
        koreanName: "고동치는달",
        imageUrl: "1005.png",
        types: ["dragon", "dark"],
    },
    {
        id: 569,
        name: "garbodor",
        koreanName: "무쇠무인",
        imageUrl: "1006.png",
        types: ["fairy", "fighting"],
    },
    {
        id: 570,
        name: "zorua",
        koreanName: "조로아(히스이)",
        imageUrl: "10238.png",
        types: ["normal", "ghost"],
    },
    {
        id: 571,
        name: "zoroark",
        koreanName: "조로아크(히스이)",
        imageUrl: "10239.png",
        types: ["normal", "ghost"],
    },
    {
        id: 572,
        name: "minccino",
        koreanName: "치라미",
        imageUrl: "572.png",
        types: ["normal"],
    },
    {
        id: 573,
        name: "cinccino",
        koreanName: "치라치노",
        imageUrl: "573.png",
        types: ["normal"],
    },
    {
        id: 574,
        name: "gothita",
        koreanName: "고디탱",
        imageUrl: "574.png",
        types: ["psychic", "dark"],
    },
    {
        id: 575,
        name: "gothorita",
        koreanName: "고디보미",
        imageUrl: "575.png",
        types: ["psychic", "dark"],
    },
    {
        id: 576,
        name: "gothitelle",
        koreanName: "고디모아젤",
        imageUrl: "576.png",
        types: ["psychic", "dark"],
    },
    {
        id: 577,
        name: "solosis",
        koreanName: "유니란",
        imageUrl: "577.png",
        types: ["psychic"],
    },
    {
        id: 578,
        name: "duosion",
        koreanName: "듀란",
        imageUrl: "578.png",
        types: ["psychic"],
    },
    {
        id: 579,
        name: "reuniclus",
        koreanName: "란쿨루스",
        imageUrl: "579.png",
        types: ["psychic"],
    },
    {
        id: 580,
        name: "ducklett",
        koreanName: "꼬지보리",
        imageUrl: "580.png",
        types: ["water", "flying"],
    },
    {
        id: 581,
        name: "swanna",
        koreanName: "스완나",
        imageUrl: "581.png",
        types: ["water", "flying"],
    },
    {
        id: 582,
        name: "vanillite",
        koreanName: "바닐프티",
        imageUrl: "582.png",
        types: ["ice", "fairy"],
    },
    {
        id: 583,
        name: "vanillish",
        koreanName: "바닐리치",
        imageUrl: "583.png",
        types: ["ice", "fairy"],
    },
    {
        id: 584,
        name: "vanilluxe",
        koreanName: "배바닐라",
        imageUrl: "584.png",
        types: ["ice", "fairy"],
    },
    {
        id: 585,
        name: "deerling",
        koreanName: "사철록",
        imageUrl: "585.png",
        types: ["normal", "grass"],
    },
    {
        id: 586,
        name: "sawsbuck",
        koreanName: "바라철록",
        imageUrl: "586.png",
        types: ["normal", "grass"],
    },
    {
        id: 587,
        name: "emolga",
        koreanName: "사나운버섯",
        imageUrl: "986.png",
        types: ["grass", "dark"],
    },
    {
        id: 588,
        name: "karrablast",
        koreanName: "딱정곤",
        imageUrl: "588.png",
        types: ["bug"],
    },
    {
        id: 589,
        name: "escavalier",
        koreanName: "슈바르고",
        imageUrl: "589.png",
        types: ["bug", "steel"],
    },
    {
        id: 590,
        name: "foongus",
        koreanName: "깜놀버슬",
        imageUrl: "590.png",
        types: ["grass", "poison"],
    },
    {
        id: 591,
        name: "amoonguss",
        koreanName: "뽀록나",
        imageUrl: "591.png",
        types: ["grass", "poison"],
    },
    {
        id: 592,
        name: "frillish",
        koreanName: "탱그릴",
        imageUrl: "592.png",
        types: ["water", "ghost"],
    },
    {
        id: 593,
        name: "jellicent",
        koreanName: "탱탱겔",
        imageUrl: "593.png",
        types: ["water", "ghost"],
    },
    {
        id: 594,
        name: "alomomola",
        koreanName: "무쇠머리",
        imageUrl: "993.png",
        types: ["dark", "flying"],
    },
    {
        id: 595,
        name: "joltik",
        koreanName: "파쪼옥",
        imageUrl: "595.png",
        types: ["bug", "electric"],
    },
    {
        id: 596,
        name: "galvantula",
        koreanName: "전툴라",
        imageUrl: "596.png",
        types: ["bug", "electric"],
    },
    {
        id: 597,
        name: "ferroseed",
        koreanName: "철시드",
        imageUrl: "597.png",
        types: ["grass", "steel"],
    },
    {
        id: 598,
        name: "ferrothorn",
        koreanName: "너트령",
        imageUrl: "598.png",
        types: ["grass", "steel"],
    },
    {
        id: 599,
        name: "klink",
        koreanName: "기어르",
        imageUrl: "599.png",
        types: ["steel"],
    },
    {
        id: 600,
        name: "klang",
        koreanName: "기기어르",
        imageUrl: "600.png",
        types: ["steel"],
    },
    {
        id: 601,
        name: "klinklang",
        koreanName: "기기기어르",
        imageUrl: "601.png",
        types: ["steel"],
    },
    {
        id: 602,
        name: "tynamo",
        koreanName: "저리어",
        imageUrl: "602.png",
        types: ["electric"],
    },
    {
        id: 603,
        name: "eelektrik",
        koreanName: "저리릴",
        imageUrl: "603.png",
        types: ["electric"],
    },
    {
        id: 604,
        name: "eelektross",
        koreanName: "저리더프",
        imageUrl: "604.png",
        types: ["electric"],
    },
    {
        id: 605,
        name: "elgyem",
        koreanName: "리그레",
        imageUrl: "605.png",
        types: ["psychic", "normal"],
    },
    {
        id: 606,
        name: "beheeyem",
        koreanName: "벰크",
        imageUrl: "606.png",
        types: ["psychic", "normal"],
    },
    {
        id: 607,
        name: "litwick",
        koreanName: "불켜미",
        imageUrl: "607.png",
        types: ["ghost", "fire"],
    },
    {
        id: 608,
        name: "lampent",
        koreanName: "램프라",
        imageUrl: "608.png",
        types: ["ghost", "fire"],
    },
    {
        id: 609,
        name: "chandelure",
        koreanName: "샹델라",
        imageUrl: "609.png",
        types: ["ghost", "fire"],
    },
    {
        id: 610,
        name: "axew",
        koreanName: "터검니",
        imageUrl: "610.png",
        types: ["dragon"],
    },
    {
        id: 611,
        name: "fraxure",
        koreanName: "액슨도",
        imageUrl: "611.png",
        types: ["dragon"],
    },
    {
        id: 612,
        name: "haxorus",
        koreanName: "액스라이즈",
        imageUrl: "612.png",
        types: ["dragon"],
    },
    {
        id: 613,
        name: "cubchoo",
        koreanName: "코고미",
        imageUrl: "613.png",
        types: ["ice"],
    },
    {
        id: 614,
        name: "beartic",
        koreanName: "툰베어",
        imageUrl: "614.png",
        types: ["ice", "fighting"],
    },
    {
        id: 615,
        name: "cryogonal",
        koreanName: "프리지오",
        imageUrl: "615.png",
        types: ["ice"],
    },
    {
        id: 616,
        name: "shelmet",
        koreanName: "쪼마리",
        imageUrl: "616.png",
        types: ["bug"],
    },
    {
        id: 617,
        name: "accelgor",
        koreanName: "어지리더",
        imageUrl: "617.png",
        types: ["bug"],
    },
    {
        id: 618,
        name: "stunfisk",
        koreanName: "모래털가죽",
        imageUrl: "989.png",
        types: ["electric", "ground"],
    },
    {
        id: 619,
        name: "mienfoo",
        koreanName: "비조푸",
        imageUrl: "619.png",
        types: ["fighting"],
    },
    {
        id: 620,
        name: "mienshao",
        koreanName: "비조도",
        imageUrl: "620.png",
        types: ["fighting"],
    },
    {
        id: 621,
        name: "druddigon",
        koreanName: "크리만",
        imageUrl: "621.png",
        types: ["dragon"],
    },
    {
        id: 622,
        name: "golett",
        koreanName: "골비람",
        imageUrl: "622.png",
        types: ["ground", "ghost"],
    },
    {
        id: 623,
        name: "golurk",
        koreanName: "골루그",
        imageUrl: "623.png",
        types: ["ground", "ghost"],
    },
    {
        id: 624,
        name: "pawniard",
        koreanName: "자망칼",
        imageUrl: "624.png",
        types: ["dark", "steel"],
    },
    {
        id: 625,
        name: "bisharp",
        koreanName: "절각참",
        imageUrl: "625.png",
        types: ["dark", "steel"],
    },
    {
        id: 626,
        name: "bouffalant",
        koreanName: "대도각참",
        imageUrl: "983.png",
        types: ["dark", "steel"],
    },
    {
        id: 627,
        name: "rufflet",
        koreanName: "수리둥보",
        imageUrl: "627.png",
        types: ["normal", "flying"],
    },
    {
        id: 628,
        name: "braviary",
        koreanName: "워글",
        imageUrl: "628.png",
        types: ["normal", "flying"],
    },
    {
        id: 629,
        name: "vullaby",
        koreanName: "벌차이",
        imageUrl: "629.png",
        types: ["dark", "flying"],
    },
    {
        id: 630,
        name: "mandibuzz",
        koreanName: "버랜지나",
        imageUrl: "630.png",
        types: ["dark", "flying"],
    },
    {
        id: 631,
        name: "heatmor",
        koreanName: "드레디어(히스이)",
        imageUrl: "10237.png",
        types: ["grass", "fighting"],
    },
    {
        id: 632,
        name: "durant",
        koreanName: "아이앤트",
        imageUrl: "632.png",
        types: ["bug", "steel"],
    },
    {
        id: 633,
        name: "deino",
        koreanName: "모노두",
        imageUrl: "633.png",
        types: ["dark", "dragon"],
    },
    {
        id: 634,
        name: "zweilous",
        koreanName: "디헤드",
        imageUrl: "634.png",
        types: ["dark", "dragon"],
    },
    {
        id: 635,
        name: "hydreigon",
        koreanName: "삼삼드래",
        imageUrl: "635.png",
        types: ["dark", "dragon"],
    },
    {
        id: 636,
        name: "larvesta",
        koreanName: "활화르바",
        imageUrl: "636.png",
        types: ["bug", "fire"],
    },
    {
        id: 637,
        name: "volcarona",
        koreanName: "불카모스",
        imageUrl: "637.png",
        types: ["bug", "fire"],
    },
    {
        id: 638,
        name: "cobalion",
        koreanName: "코바르온",
        imageUrl: "638.png",
        types: ["steel", "fighting"],
    },
    {
        id: 639,
        name: "terrakion",
        koreanName: "테라키온",
        imageUrl: "639.png",
        types: ["rock", "fighting"],
    },
    {
        id: 640,
        name: "virizion",
        koreanName: "비리디온",
        imageUrl: "640.png",
        types: ["grass", "fighting"],
    },
    {
        id: 641,
        name: "tornadus-incarnate",
        koreanName: "토네로스",
        form: [
            {
                formName: "화신폼",
                imageUrl: "641.png",
                types: ["flying"],
            },
            {
                formName: "영물폼",
                imageUrl: "10019.png",
                types: ["flying"],
            },
        ],
    },
    {
        id: 642,
        name: "thundurus-incarnate",
        koreanName: "볼트로스",
        form: [
            {
                formName: "화신폼",
                imageUrl: "642.png",
                types: ["electric", "flying"],
            },
            {
                formName: "영물폼",
                imageUrl: "10020.png",
                types: ["electric", "flying"],
            },
        ],
    },
    {
        id: 643,
        name: "reshiram",
        koreanName: "레시라무",
        imageUrl: "643.png",
        types: ["dragon", "fire"],
    },
    {
        id: 644,
        name: "zekrom",
        koreanName: "제크로무",
        imageUrl: "644.png",
        types: ["dragon", "electric"],
    },
    {
        id: 645,
        name: "landorus-incarnate",
        koreanName: "랜드로스",
        form: [
            {
                formName: "화신폼",
                imageUrl: "645.png",
                types: ["ground", "flying"],
            },
            {
                formName: "영물폼",
                imageUrl: "10021.png",
                types: ["ground", "flying"],
            },
        ],
    },
    {
        id: 646,
        name: "kyurem",
        koreanName: "큐레무",
        form: [
            {
                formName: "일반",
                imageUrl: "646.png",
                types: ["dragon", "ice"],
            },
            {
                formName: "블랙",
                imageUrl: "10022.png",
                types: ["dragon", "ice"],
            },
            {
                formName: "화이트",
                imageUrl: "10023.png",
                types: ["dragon", "ice"],
            },
        ],
    },
    {
        id: 647,
        name: "keldeo-ordinary",
        koreanName: "케르디오",
        form: [
            {
                formName: "일반",
                imageUrl: "647.png",
                types: ["water", "fighting"],
            },
            {
                formName: "각오",
                imageUrl: "10024.png",
                types: ["water", "fighting"],
            },
        ],
    },
    {
        id: 648,
        name: "meloetta-aria",
        koreanName: "메로엣타",
        form: [
            {
                formName: "보이스폼",
                imageUrl: "648.png",
                types: ["normal", "psychic"],
            },
            {
                formName: "스텝폼",
                imageUrl: "10018.png",
                types: ["normal", "fighting"],
            },
        ],
    },
    {
        id: 649,
        name: "genesect",
        koreanName: "게노세크트",
        imageUrl: "649.png",
        types: ["bug", "steel"],
    },
]